spring:
  application:
    name: zuul-service

server:
  port: 5555

zuul:
  routes:
    ribbon-compute-service:
      path: /ribbon-compute/**
      service-id: ribbon-service
    feign-compute-serivce:
      path: /feign-compute/**
      service-id: feign-service
  ribbon:
    eager-load:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
